name: Sync Fork with Upstream (Rebase)

# Controls when the action will run.
on:
  # Runs on a schedule (every 6 hours). You can adjust the cron schedule as needed.
  schedule:
    - cron: '0 18 * * *'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the fork's code
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          # Fetch all history for all branches and tags
          fetch-depth: 0
      # 2. Generate a token from the GitHub App
      - name: Generate GitHub App Token
        id: get_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      # 3. Set up Git configuration
      - name: Set up Git
        run: |
          git config --global user.name "krishukr[bot]"
          git config --global user.email "krishukr[bot]@users.noreply.github.com"
      # 4. Perform the sync and rebase
      - name: Rebase Upstream
        uses: imba-tjd/rebase-upstream-action@0.12
        with:
          # <user>/<repo> or the full HTTP URL
          upstream: cinnyapp/cinny
          # The upstream branch that is rebased on
          branch: dev
          # GitHub token to access to API and git
          token: ${{ steps.get_token.outputs.token }}
